from http.client import REQUEST_TIMEOUT


REQUEST_TIMEOUT = 3

COMMAND_LOGIN = 'LOGIN'
COMMAND_GET_CONF = 'GET_CONFIGURATION'
COMMAND_GET_MULTI_STATES = 'GET_MULTIPLE_STATES'
TOKEN_KEY = 'token'
COMMAND_KEY = 'command'
PARAMS_KEY = 'params'
USER_KEY = 'username'
PASS_KEY = 'password'
COMMANDS_URL = 'commands'

TYPE_DIMMER = 'DIMMER'
TYPE_REPEATER = 'REPEATER'
TYPE_SWITCH = 'SWITCH'
TYPE_SHUTTER = 'SHUTTER'
TYPE_TWO_WAY = 'TWO_WAY'
TYPE_GROUP_SWITCH = 'GROUP_SWITCH'
TYPE_SCENARIO = 'SCENARIO'
TYPE_TIMED_POWER = 'TIMED_POWER'

SUPPORTED_ITEMS = [TYPE_DIMMER, TYPE_SWITCH, TYPE_SHUTTER]